Default:
  lr: 5e-4
  idm_lr: 5e-4
  idm: 'CnnPolicy'
  policy: 'CnnPolicy'
  random_episodes: 10000

Maze:
  lr: 5e-4
  idm_lr: 5e-4
  idm: 'CnnPolicy'
  policy: 'CnnPolicy'
  random_episodes: 10000

Maze-v0:
  lr: 5e-4
  idm_lr: 5e-4
  idm: 'CnnPolicy'
  policy: 'CnnPolicy'
  random_episodes: 10000
